name: eggnstone_google_crashlytics
copyright: 2020-2022 Mark Eggenstein
description: A wrapper for Google Crashlytics. Allows to report via Firebase.
homepage: https://github.com/eggnstone/eggnstone_google_crashlytics
version: 3.4.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter tools
  eggnstone_flutter: ^3.4.1
  #eggnstone_flutter:
  #  path: ../eggnstone_flutter

  # Google/Firebase Crashlytics, logging crashes
  firebase_crashlytics: ^2.8.1
  # Service locator (included via eggnstone_flutter but "flutter pub publish" warns if not included here)
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
