name: eggnstone_google_crashlytics
copyright: 2020-2021 Mark Eggenstein
description: Google Crashlytics wrapper. Allows to report via Firebase.
homepage: https://github.com/eggnstone/eggnstone_google_crashlytics
version: 0.3.5

# Default package versions on 18.02.2021
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter tools
  eggnstone_flutter: ^0.3.5
  #eggnstone_flutter:
  #  path: ..\eggnstone_flutter

  # Google/Firebase Crashlytics, logging crashes
  firebase_crashlytics: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
